export type Spot = { id: string; label: string; x: number; y: number; w?: number; h?: number; to?: string; text?: string; edge?: boolean; sound?: 'stone'|'water' };
export type View = { room: string; art: string; title: string; facing: string; alt: string; turn?: string; parent?: string; zoom?: [number,number,number]; spots: Spot[] };
const go=(id:string,label:string,x:number,y:number,to:string,w=14,h=28):Spot=>({id,label,x,y,to,w,h});
const back=(to:string,label='Step back'):Spot=>({...go('back',label,50,87,to,24,12),edge:true});
const look=(id:string,label:string,x:number,y:number,to:string):Spot=>go(id,label,x,y,to,12,17);
export const rooms:Record<string,{name:string;x:number;y:number;level:number}>={
 entrance:{name:'Headless saint',x:90,y:310,level:0},gallery:{name:'Blue gallery',x:90,y:185,level:0},chapel:{name:'Chapel',x:90,y:60,level:0},crypt:{name:'Crypt',x:390,y:60,level:0},watercourse:{name:'Watercourse',x:240,y:185,level:-1},cistern:{name:'Cistern',x:390,y:185,level:-1},stair:{name:'Return stair',x:390,y:310,level:-1}
};
export const connections=[['entrance','gallery'],['gallery','chapel'],['chapel','crypt'],['crypt','cistern'],['cistern','stair'],['stair','entrance'],['gallery','watercourse'],['watercourse','cistern']];
export const views:Record<string,View>={
 entrance:{room:'entrance',art:'entrance',title:'The headless saint',facing:'At the threshold',alt:'A headless saint beside a blue-banded gallery. A stair descends to the right.',spots:[go('gallery','Follow the blue tiles',40,48,'gallery',20,48),go('stair','Go down beside the iron rail',86,58,'stair',20,48),look('saint','Approach the saint',15,40,'saint')]},
 gallery:{room:'gallery',art:'gallery',title:'The blue gallery',facing:'Toward the chapel',alt:'A low processional gallery. The chapel lies ahead; a wet passage slopes away to the right.',turn:'gallery-back',spots:[go('chapel','Continue into the chapel',50,48,'chapel',17,36),go('watercourse','Follow the water downhill',85,55,'watercourse',17,35),look('tiles','Examine the broken tiles',24,56,'tiles')]},
 'gallery-back':{room:'gallery',art:'gallery-back',title:'The blue gallery',facing:'Toward the entrance',alt:'The saint is visible through the far arch. The wet passage is now on the left.',turn:'gallery',spots:[go('entrance','Return to the saint',50,50,'entrance',20,40),go('watercourse','Follow the water downhill',20,57,'watercourse',17,35)]},
 chapel:{room:'chapel',art:'chapel',title:'The quiet chapel',facing:'Beneath the broken rose',alt:'A bare altar under a broken stone rose. A side arch opens into the crypt.',turn:'chapel-back',spots:[look('altar','Walk between the benches',50,57,'altar'),go('crypt','Pass behind the altar',89,48,'crypt',16,37)]},
 'chapel-back':{room:'chapel',art:'chapel-back',title:'The quiet chapel',facing:'Looking back along the processional route',alt:'From beside the altar, the gallery runs away through the south door. The crypt opens on the left.',turn:'chapel',spots:[go('gallery','Walk back into the gallery',50,48,'gallery-back',19,39),go('crypt','Enter the burial passage',15,53,'crypt',17,42)]},
 crypt:{room:'crypt',art:'crypt',title:'The burial passage',facing:'Beyond the chapel',alt:'Empty burial shelves line the wall. Mineral streaks descend toward a stair on the right.',turn:'crypt-back',spots:[go('cistern','Descend below the chapel',88,58,'cistern',19,42),look('alcove','Look inside the low alcove',25,58,'alcove')]},
 'crypt-back':{room:'crypt',art:'crypt-back',title:'The burial passage',facing:'Toward the altar',alt:'The chapel is visible through the west doorway. Stairs descend on the left.',turn:'crypt',spots:[go('chapel','Return beside the altar',50,49,'chapel-back',18,38),go('cistern','Descend below the chapel',18,56,'cistern',18,40)]},
 cistern:{room:'cistern',art:'cistern',title:'Below the waterline',facing:'On the cistern ledge',alt:'A broken column stands in dark water. Ledges connect an ascending ramp and the crypt stairs.',spots:[go('crypt','Climb toward the burial niches',70,32,'crypt-back',16,30),go('watercourse','Climb the sloping watercourse',12,35,'watercourse',15,32),look('water','Kneel at the water',50,76,'water'),back('stair','Follow the ledge to the return stair')]},
 watercourse:{room:'watercourse',art:'watercourse',title:'The watercourse',facing:'Between the gallery and the cistern',alt:'Water runs downhill beside a dry walkway. Blue tiles above; dark water below.',spots:[go('gallery','Climb to the blue tiles',15,44,'gallery-back',20,48),go('cistern','Follow the channel to the cistern',78,52,'cistern',23,44),look('seam','Examine the mineral seam',46,60,'seam')]},
 stair:{room:'stair',art:'stair',title:'The return stair',facing:'The saint above; water below',alt:'An iron rail follows the stairs up to the familiar headless saint. A lower arch opens onto the cistern.',spots:[go('entrance','Climb back to the saint',39,36,'entrance',24,40),go('cistern','Step onto the cistern ledge',84,64,'cistern',22,46)]},
 saint:{room:'entrance',art:'entrance',title:'An empty offering',facing:'Beside the saint',alt:'The saint’s empty stone bowl, held in worn hands.',parent:'entrance',zoom:[2.7,18.6,37],spots:[{id:'bowl',label:'Touch the worn bowl',x:40,y:42,w:24,h:30,text:'The rim is polished smooth. Countless hands paused here before entering.',sound:'stone'},back('entrance')]},
 tiles:{room:'gallery',art:'gallery',title:'The broken blue band',facing:'At the gallery wall',alt:'Faded blue tiles set into rough limestone.',parent:'gallery',zoom:[2,24,56],spots:[{id:'band',label:'Follow the pattern',x:46,y:52,w:30,h:30,text:'The same blue band runs from the saint to the altar. Here, water has loosened the mortar.'},back('gallery')]},
 altar:{room:'chapel',art:'chapel',title:'Beneath the stone rose',facing:'At the altar',alt:'A bare stone altar beneath a ruined circular carving.',parent:'chapel',zoom:[1.7,50,46],spots:[{id:'stone',label:'Rest your hand on the altar',x:50,y:67,w:35,h:22,text:'The top is cold. A faint hollow note lingers under the vault.',sound:'stone'},back('chapel','Step back between the benches')]},
 alcove:{room:'crypt',art:'crypt',title:'A place for one small thing',facing:'Inside the burial alcove',alt:'A worn burial niche in the crypt wall.',parent:'crypt',zoom:[2,25,53],spots:[{id:'clay',label:'Look closer at the stone shelf',x:48,y:55,w:35,h:35,text:'No inscription survives. The stone shelf is worn smooth at the edge.'},back('crypt')]},
 water:{room:'cistern',art:'cistern',title:'At the water’s edge',facing:'Kneeling below the chapel',alt:'Lantern light on dark cistern water beside a broken column.',parent:'cistern',zoom:[1.5,52,72],spots:[{id:'ripple',label:'Touch the water',x:50,y:62,w:55,h:40,text:'The reflection breaks. Small rings reach the broken pillar and come back.',sound:'water'},back('cistern','Stand up on the ledge')]},
 seam:{room:'watercourse',art:'watercourse',title:'What the water remembers',facing:'Along the sloping channel',alt:'White mineral deposits trace the passage downhill.',parent:'watercourse',zoom:[1.8,46,60],spots:[{id:'mineral',label:'Trace the old waterline',x:49,y:52,w:36,h:34,text:'A pale line continues down the passage. The cistern once stood much higher.'},back('watercourse')]}
};
export const artUrls=Object.fromEntries(Object.entries(import.meta.glob('../assets/underchapel/*.webp',{eager:true,query:'?url',import:'default'})).map(([path,url])=>[path.split('/').pop()!.replace('.webp',''),url as string]));
